### ISSUE TITLE
Playground: upload component modifications

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#121]
# Playground: upload component modifications

![image](https://user-images.githubusercontent.com/97060856/227624773-aa540e07-98c1-40b8-abc5-f97649422fa3.png)

## To Do
- [ ] Update the content of the instructions to the content specified in the Figma file.
- [ ]  Add a divider, a "New" badge, and content to the instructions container
- [ ]  Implement spacing and layout adjustments in the upload interface
- [ ]  Color the asterisk after "Data" red
- [ ]  Implement the Upload File button update
- [ ]  Implement the No file loaded copy under the new Upload button

## Resources

- [Figma design file: Playground upload component](https://www.figma.com/file/u9SoNtpqNORA758srXVALQ/ASCT%2BB-Reporter?node-id=106-230&t=QfaUYntIWmFfibPy-4)
- OMAP Compare Template (Link to be added when it is delivered to me)

## User Stories
- As a user, I want to know what data I can upload into the Playground, so that I can generate useful visualizations and reports from the ASCT+B Reporter.
- As a user, I want to have helpful instructions, so that I can successfully use this feature.
- As a user, I want the upload component to be intuitive, so that I can quickly generate visualizations and reports that further my research.
- As a user, I want a button with an upload icon instead of a vague attachment icon without a label, so that I can learn how to use this interface faster.

**Comment by bherr2** [comment]
@libby-maier any reason why you closed this?

**Comment by libby-maier** [comment]
Wrong Repo - Apologies! I didn't know how to delete it, so I closed it and recreated it in CCF ASCT Reporter: https://github.com/hubmapconsortium/ccf-asct-reporter/issues/622

**Comment by bherr2** [comment]
Oh right, got it! I'll actually delete this one for you.
