### ISSUE TITLE
Update usage metrics page for 5th release

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#156]
https://humanatlas.io/usage-metrics has really low resolution images. Please revisit [the source page](https://docs.google.com/document/d/1LNMrkg5dndYLbUnqjHhk5IeTBqTnXuUSpzVf7wFbXic/edit#) and get better images and don't scale up images to fit width.

**Comment by libby-maier** [comment]
Hi @bherr2, I am renaming and repurposing this issue for updating HRA Portal [Usage Metrics](https://humanatlas.io/usage-metrics). Tomorrow Lisel and I will work to generate content for Training Materials metrics and Diversity Survey metrics.

### To Do
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/4a9f6d15-e35f-4f60-93c2-6b821b8bebc6)

- [ ] Update Software section text and screenshots for 2023 Google Analytics metrics
- [ ] Add updated Training Materials metrics from [Usage Metrics Google Doc](https://docs.google.com/document/d/1bGX8zrQsSw3Kutz0PFKrX2L1GHGFQanpe9IBPPRiPfo/edit#heading=h.k913kuu1t5x3)
- [ ] Add new Diversity Metrics section from [Usage Metrics Google Doc](https://docs.google.com/document/d/1bGX8zrQsSw3Kutz0PFKrX2L1GHGFQanpe9IBPPRiPfo/edit#heading=h.k913kuu1t5x3)

**Comment by bherr2** [comment]
On hold until we can get better usage metrics and of higher fidelity

**Comment by libby-maier** [comment]
This item will not be featured in the 6th in this capacity and is not slated for the navigation structure currently in the 7th release. I labeled as wontfix and I am closing this issue. Thanks!
