### ISSUE TITLE
Remove CCF in title cards to match Figma

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#166]
# Remove CCF in title cards to match Figma 

We removed CCF from title cards in Figma in late 2022. Please mirror Figma and remove CCF in the below title cards from the production site.

## To Do 
Remove CCF from the following title cards:
- [x] https://humanatlas.io/asctb-tables
- [x] https://humanatlas.io/2d-ftu-illustrations?version=1.3&organ=Kidney
- [x] https://humanatlas.io/3d-reference-library?version=1.3&organ=Allen%20Brain
- [x] https://humanatlas.io/asctb-reporter
- [x] https://humanatlas.io/exploration-user-interface

![image](https://user-images.githubusercontent.com/97060856/235772832-6af738a1-3da7-49d9-bdc2-b279547a3507.png)
![image](https://user-images.githubusercontent.com/97060856/235773079-63ccb892-b7c0-43e7-b157-4244e09a0fd7.png)
![image](https://user-images.githubusercontent.com/97060856/235773277-4273abf8-54e3-45d5-9e4f-0fc6d26f824f.png)
![image](https://user-images.githubusercontent.com/97060856/235773347-4001191f-bb8a-4daf-ab92-7796bd8d18fb.png)
![image](https://user-images.githubusercontent.com/97060856/235773525-9d30025c-4d71-47e6-814d-637dd55c6acc.png)

**Comment by bhushankhope** [comment]
Fixed this in #172
