### ISSUE TITLE
Update SOP links on ASCT+B Table page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#167]
# Update SOP links on [ASCT+B Table page](https://humanatlas.io/asctb-tables)

SOP links need to be updated to the following URLs:

- [ ] [SOP: Authoring Anatomical Structures, Cell Types and Biomarkers (ASCT+B) Tables](https://zenodo.org/record/7382751#.ZFPCXXbMK3A)
- [ ] [SOP: ASCT+B Table Communications](https://zenodo.org/record/5639623#.ZFPCYHbMK3A)

External links should always open in new tabs.

Tagging @emquardokus so she can track this issue and comments can be resolved in the [ASCT+B Table doc](https://docs.google.com/document/d/12tCFvt4r9iFWeq4A8BumHGgu-opY7YdxVAZoczZeM74/edit#heading=h.187laarduava). Thank you!

**Comment by bhushankhope** [comment]
Fixed this in #173
