### ISSUE TITLE
Add a fading effect to the right side of tables with horizontal scrolling

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#168]
# Add a fading effect to the right side of tables with horizontal scrolling
The larger tables that necessitate a horizontal scroll bar need to have a fading effect on the right side. This is to indicate to users that they can scroll horizontally. 

@bherr2 mentioned that he can assist with this if @bhushankhope needs help.

Currently, the ASCT+B Table page is the only area requiring this, but should tables expand elsewhere, the functionality will need to be mirrored there.

## To Do
- [ ] Add fading effect to the right side of the table on any tables with horizontal scrolling.

### Resources
- [Example: Exploration User Interface for lower right side vertical scrolling fade](https://portal.hubmapconsortium.org/ccf-eui)
- [GitHub Link from Bruce](https://github.com/hubmapconsortium/ccf-ui/blob/de5cc39765dc68ea3ba74255d973418f2ac18c04/projects/ccf-eui/src/app/modules/results-browser/results-browser/results-browser.component.ts#L102-L109)

### Example: Exploration User Interface's lower right side vertical scrolling fade
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/e9bf0e70-1d80-4ac2-8163-bdeeb1497e05)

**Comment by bhushankhope** [comment]
Added this feature in PR #187
