### ISSUE TITLE
Symbol for ovary shows entire female reproductive system

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/humanatlas.io#170]
A SME pointed out to me that the symbol for ovary shows entire female reproductive system. Should consider remaking SVG to only show ovary. 

![image](https://github.com/cns-iu/humanatlas.io/assets/22821046/2fc68568-63aa-410c-9710-a7917a127f72)

**Comment by bherr2** [comment]
@bhushankhope not actionable right now. @libby-maier @katyb please consider a solution.

**Comment by libby-maier** [comment]
I propose we move away from the organ icons for the 6th release. 

The many organ icons in our interfaces require much upkeep from designers and developers. The 3D ref page is a great example of too many icon button options. 

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/dc587a1d-8db5-4d6e-9d05-3dcf4a100b8f)

As we learned last year during EUI spatial search testing, experts prefer alphabetical, dropdown listings. Using a listing instead of organ icon buttons moves us closer to our evergreen content goal for the HRA Portal.

**Comment by andreasbueckle** [comment]
I disagree. The icons fulfill a valuable aesthetic role. The carousel in the EUI and the organ selection screen in the standalone RUI depend on these to fill screen estate and place the organs prominently. The new HRA Organ Gallery organ selection keyboard utilizes them prominently to make buttons with protruded 3D organ reliefs etched in. They are an essential visual component of the HRA. I agree that dropdowns are useful also, but they are not mutually exclusive with icons. We can always pair icons with text to ease search.

**Comment by bherr2** [comment]
Is a useful compromise for places where a dropdown makes more sense to include the icon + text?

**Comment by andreasbueckle** [comment]
Of course! I am not arguing to integrate the icons everywhere, but I think we should not neglect their upkeep, given their many use cases.

**Comment by emquardokus** [comment]
I agree with @andreasbueckle  in that a visual representation of each organ plus label and a drop-down where that may fulfill a different user pool. Once icons are made, I’m not sure I understand what further maintenance they require? Drop-down menus can become unwieldy too when too long so I’m not sure that argument for them over icons really makes sense?
@libby-maier how many experts were polled? I’m curious. It might also matter what their background is for preferences. Was this a formal user study of the interface in general?

**Comment by emquardokus** [comment]
@HeidiS25 do you have an ovary icon?

**Comment by libby-maier** [comment]
I removed my assignment from this task as I do not design organ icons for HRA. @HeidiS25, could you make us an ovary icon and link me to it upon completion?

@emquardokus - Updating the icons every release requires design and development labor that may not be necessary if experts have different preferences. We conducted moderated usability tests with 4 RUI experts in the spring of 2022 for the EUI spatial search. We presented them with three options: icons + text listing, dropdown listing, and a search input with auto-complete. They unanimously agreed that remembering icons for specific organs or searching without knowing the options was difficult and preferred the dropdown. Devin has also received negative feedback on the RUI organ icon listings, though I'm not sure to what extent.

I will run a survey to see what people prefer in our various interfaces for the 6th release. Thanks!

**Comment by emquardokus** [comment]
@libby-maier it would be really valuable to see the comments so we could address them when they come. I was really surprised to see this; first I had heard anything about it. Thank-you
Also I don’t really understand what “updating the icons” really means here since it seems like they exist already— what is actually required? It helps to know for the multidisciplinary group who are not designers per se. Thanks again.

**Comment by andreasbueckle** [comment]
@emquardokus Yes, these icons exist. What started this issue was that a SME mentioned that the existing one for ovary also shows other organs (Fallopian tubes, uterus) and suggested that we update it. This entails changing the SVG file and having it reviewed, which takes time by either @HeidiS25 or @libby-maier. That's what updating the icons means. 

Heidi or Libby, I am happy to help with this process. If we keep using the icons, we should make sure they are anatomically sound.

**Comment by andreasbueckle** [comment]
OK, I think I found a solution. We actually have 3 icons for the ovary: 
(ovaries.svg)[https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-eui/src/assets/icons/organs/ico-organs-ovaries.svg]
(ovary-left.svg)[https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-eui/src/assets/icons/organs/ico-organs-ovaries.svg]
(ovary-right.svg)[https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-eui/src/assets/icons/organs/ico-organs-ovaries.svg]

So we DO have a correct version for each individual one, it's just a matter of using the right icons at the right place. No action needed and closing this.

**Comment by emquardokus** [comment]
@andreasbueckle yes, I was 100% certain we had left and right ovary because I remembered reviewing these.  The wrong icons were used on HRA portal, the correct ones were used in the RUI for left or right.

**Comment by andreasbueckle** [comment]
@emquardokus 
I think we are using the right ones here because we show all ovaries not just L or R: https://humanatlas.io/3d-reference-library
As for their usage in RUI and EUI, I would argue that we need to swap them, see https://github.com/hubmapconsortium/ccf-ui/pull/1051
