### ISSUE TITLE
Incorrect link in HRA portal

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#171]
On the following website, "FAQ: Frequently Asked Questions (FAQ) for Organ Mapping Antibody Panels (OMAPs)" is linked to FAQ for AVRs".
https://humanatlas.io/standard-operating-procedures

**Comment by libby-maier** [comment]
Hi @jianghuayu007, this will be corrected in the 5th release. @bhushankhope has updated this on the staging website. Thanks for bringing this to our attention!

**Comment by bherr2** [comment]
It's live 🎉
