### ISSUE TITLE
3D Reference Object Page - Add L to male right kidney

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#174]
### To-Do: High Priority
- [ ] Add Male, L title to the male left kidney on the [3D Reference Object Kidney page](https://humanatlas.io/3d-reference-library?version=1.3&organ=Kidney).

The [HRA-UI mono repo](https://github.com/hubmapconsortium/hra-ui) contains one HRA Portal issue currently: https://github.com/hubmapconsortium/hra-ui/issues/184

Please address this ASAP so that we can close out both issues.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/f77b618f-6b25-4529-a300-27f464464bcb)

**Comment by bhushankhope** [comment]
fixed this in #175
