### ISSUE TITLE
Remove items not released from Release notes v1.4

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#202]
These items had been planned for 5th release, but were not DOI'd and not released. 
More discussion and data format is being discussed before they are released in probably the 6th (v1.5) release. 
**Please remove from HRA portal page: https://humanatlas.io/release-notes/v1.4**

2 Physiological organ system tables: Male and female
3 Azimuth crosswalks: Kidney, lung, heart
24 Atlas-to-Atlas projections to/from 500 donor kidney, Allen brain, SPARC heart, SPARC colon, 1D Helmsley colon

**Comment by libby-maier** [comment]
Thank you @emquardokus & @bhushankhope!

**Comment by emquardokus** [comment]
thank you both as well! @bhushankhope! @ libby-maier
