### ISSUE TITLE
Download component for 2D & 3D pages

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#207]
# Download component for 2D & 3D pages
The 2D illustrations page and the 3D objects page each have a download section. As we continue releasing new digital objects, these sections are becoming less user-friendly with long text-based listings. We need to improve this section by adding our release dropdown and a table with download options. 

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/d254a448-e713-44e4-83eb-462803a90652)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/e1c250d7-f168-43c0-a1ab-986ecbadd81f)

## To Do
- [ ] Implement dropdown and download table on 2D illustration page.
- [ ] Implement dropdown and download table on 3D object page.

## Resources
- [Figma design file: 2D downloads](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=537-8848&t=an5PNYMYyapCxwtH-4)
- [Figma design file: 3D downloads](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4280-35127&t=an5PNYMYyapCxwtH-4)

## Correspondence
- Katy's notes in [Staging Proofread doc](https://docs.google.com/document/d/16I7EIF4qSAH9s2K1cZZGPoEKinOv5FIDyhuTaq1958o/edit#heading=h.xn44xm4cg61g):
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/3e11937d-1933-413c-b444-7d480fe4a21e)

**Comment by libby-maier** [comment]
@bhushankhope - Katy wants this to be prioritized so I added the high-priority tag. Thanks!

**Comment by emquardokus** [comment]
@bhushankhope 
Attached csv has all checked links to different files, folders, or metadata. 

NOTE:  Male release v1.3 does NOT have ANY extraction sites folder because no new models for male were released.

[LinksTo3DrefOrganFiles-07-18-2023.csv](https://github.com/cns-iu/humanatlas.io/files/12087930/LinksTo3DrefOrganFiles-07-18-2023.csv)

**Comment by libby-maier** [comment]
Thanks so much for knocking this out, @bhushankhope!
