### ISSUE TITLE
Fix typo on VCCF page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#208]
- [ ] In the Citation section on [the VCCF page](https://humanatlas.io/vccf), please remove the space between " Anatomical structures:

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/7f96c8ac-fc47-4631-8071-4a25c5b127d9)

**Comment by bhushankhope** [comment]
Fixed this in PR #214
