### ISSUE TITLE
Navigation verbiage updates: Tools Overview page, Tools navbar menu, and a couple of pages

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#211]
# To Do
- [x] Tools Overview page: Remove CCF from all button cards
- [x] Tools Overview page: Remove HRA or Human Reference Atlas from button cards
- [x] Tools Overview page: Update HRA Organ VR gallery to Organ Gallery in VR
- [x] Tools Overview page: Add (APIs) at the end of the APIs button card.
- [x] Tools navigation menu: Update HRA Organ VR gallery to Organ Gallery in VR
- [x] Tools navigation menu: Update HRA Millitome to Millitome
- [x] Tools navigation menu: Update Application Programming Interfaces to Application Programming Interfaces (APIs)
- [x] [API page](https://humanatlas.io/api): Update the title card's title from Human Reference Atlas Application Programming Interfaces to Application Programming Interfaces (API)
- [x] [Millitome page](https://humanatlas.io/hra-millitome): Update the title card's title from Human Reference Atlas Millitome to Millitome

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/130b31c9-3c47-40e6-9010-12055c38d4f4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/669ece01-25d1-4451-b966-59255a23f6f9)

## Resources
- [Figma design file: Tools Overview page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=464-8085&t=an5PNYMYyapCxwtH-4)
- [Figma design file: Tools navigation menu](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=327-5921&t=an5PNYMYyapCxwtH-4)
- [Figma design file: Millitome page title card](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=365-5404&t=an5PNYMYyapCxwtH-4)
- [Figma design file: APIs page title card](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=519-8622&t=an5PNYMYyapCxwtH-4)
- [5th Staging Proofread doc](https://docs.google.com/document/d/16I7EIF4qSAH9s2K1cZZGPoEKinOv5FIDyhuTaq1958o/edit#heading=h.tml2c99dm0io)

**Comment by bhushankhope** [comment]
Made all the changes mentioned above in PR #212

**Comment by bhushankhope** [comment]
@libby-maier I realized that some of the routes have hra in them. For example 
- https://humanatlas.io/hra-organ-gallery-in-vr
- https://humanatlas.io/hra-millitome
Please let me know if we need to update them as well.

**Comment by libby-maier** [comment]
Please remove hra from the routes as well. Thanks for catching this, @bhushankhope!

**Comment by bhushankhope** [comment]
Removed HRA from routes. @libby-maier
