### ISSUE TITLE
Fix typo on About the Team

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#216]
## Fix typo on About the Team

There is a typo in the references section of the [About the Team page](https://humanatlas.io/team):

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/708da42a-c9af-4db9-9837-7464e62abccb)

Current:
> Snyder, Michael P., Shin Lin, Amanda Posgai, Mark Atkinson, Aviv Regev, Jennifer Rood, Orit Rozenblatt-Rosen, Leslie Gaffney, Anna Hupalowska, Rahul Satija, Nils Gehlenborg, Jay Shendure, Julia Laskin, Pehr Harbury, Nicholas A. Nystrom, Jonathan C. Silverstein, Ziv Bar-Joseph, Kun Zhang, Katy Börner, Yiing Lin, Richard Conroy, Dena Procaccini, Ananda L. Roy, Ajay Pillai, Marishka Brown, and Zorina S. Galis. 2019. [The Human Body at Cellular Resolution: The NIH Human Biomolecular AtlasProgram.](https://cns.iu.edu/docs/publications/2019-Snyder-HuBMAP.pdf) Nature 574: 187-192. doi:10.1038/s41586-019-1629-x.

Fixed version:
> Snyder, Michael P., Shin Lin, Amanda Posgai, Mark Atkinson, Aviv Regev, Jennifer Rood, Orit Rozenblatt-Rosen, Leslie Gaffney, Anna Hupalowska, Rahul Satija, Nils Gehlenborg, Jay Shendure, Julia Laskin, Pehr Harbury, Nicholas A. Nystrom, Jonathan C. Silverstein, Ziv Bar-Joseph, Kun Zhang, Katy Börner, Yiing Lin, Richard Conroy, Dena Procaccini, Ananda L. Roy, Ajay Pillai, Marishka Brown, and Zorina S. Galis. 2019. [The Human Body at Cellular Resolution: The NIH Human Biomolecular Atlas Program.](https://cns.iu.edu/docs/publications/2019-Snyder-HuBMAP.pdf) Nature 574: 187-192. doi:10.1038/s41586-019-1629-x.

## To Do:
- [ ] Fix this typo on the [About the Team page](https://humanatlas.io/team)

**Comment by bhushankhope** [comment]
This is resolved

**Comment by libby-maier** [comment]
Thank you, @bhushankhope!
