### ISSUE TITLE
Update Lung icon button on 2D & 3D pages

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#218]
# Update Lung icon button on 2D & 3D pages

We have updated the verbiage of the Lungs icon button to Lung: 

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/1d781350-a15c-4910-ab71-88a09d2d45b5)

## To Do
- [ ] Replace the old Lungs icon button for new Lung icon button on 2D page.
- [ ] Replace the old Lungs icon button for new Lung icon button on 3D page.
- [ ] Update the scrollbar for smaller breakpoints to say Lung instead of Lungs.

## Resources
- [Figma design file: Lung icon button component](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=532-9091&mode=design&t=WoWcBJyHggjgaMfB-4)
- [Figma design file: 2D page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=537-9058&mode=design&t=WoWcBJyHggjgaMfB-4)
- [Figma design file: 3D page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=2079-11626&mode=design&t=WoWcBJyHggjgaMfB-4)

**Comment by bhushankhope** [comment]
Completed this in PR #222
