### ISSUE TITLE
ADD column to summary OMAP table in omaps_release5.csv file 

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#220]
** I discussed with @bherr2 adding a column called "representative dataset" next to the download for OMAP file 
** Please also change "download" to "download OMAP" to be more clear since there will be 3 links next to each other and we also call OMAPs "data"
** I've modified the download for OMAP file to add the links to all but 2 of the representative datasets for the 13 OMAPs; still working on obtaining the last 2 as public datasets.
[omaps_release5.csv](https://github.com/cns-iu/humanatlas.io/files/11895851/omaps_release5.csv)

**Comment by bhushankhope** [comment]
Completed this in PR #221

**Comment by bhushankhope** [comment]
Added the column in PR #228
