### ISSUE TITLE
Add Kaggle 3 to Training & Outreach Overview page + nav bar menus

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#231]
## Add Kaggle 3 to Training & Outreach Overview page + nav bar menus

Please add links to Kaggle 3 to the HRA Portal.
> https://www.kaggle.com/competitions/hubmap-hacking-the-human-vasculature

This is an external link so it will open in a new tab. We will have a content page for K3 eventually when the competition is over.

## To Do
- [x] Add K3 button card to Training & Outreach Overview
- [x] Add K3 menu item to Training & Outreach navigation menu on mobile/desktop.

## Resources
- [Figma Design File: Training & Outreach Overview](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=464-8213&mode=design&t=6uNV2bw2n5fVxpI8-4)
- [Figma Design File: Desktop Navbar](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=327-5740&mode=design&t=6uNV2bw2n5fVxpI8-4)
- [Figma Design File: Mobile Navbar](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=3351-14125&mode=design&t=6uNV2bw2n5fVxpI8-4)

**Comment by bhushankhope** [comment]
Completed this in PR #233
