### ISSUE TITLE
3D Reference Page: Add a table with AS per Organ & Uberon IDs

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#232]
# 3D Reference Page: Add a table with AS per Organ & Uberon IDs

A table featuring the number of AS per reference organ and Uberon IDs needs to be added to the 3D reference object page. The release dropdown component will control this table. Users have the option to download this file as a CSV or XLSX.

Please note that mock data is used in the Figma design file:

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/35e59d2c-21a5-4bef-86f4-c3479a35229b)

## To Do
- [ ] Add the new table to the 3D reference object page.

## Resources
- [Figma design file: New Table on 3D Page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4532-35944&mode=design&t=6uNV2bw2n5fVxpI8-4)
- [Bruce's Asana To Do](https://app.asana.com/0/1204203031653102/1204982926081312/f)

## Correspondence
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/f4dd5e46-0f6a-47fa-bd25-23fc6e8018b1)
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/39656bda-7200-4a1d-9ab3-d6f63d943b6d)

**Comment by libby-maier** [comment]
Is this still necessary with the major changes to the HRA Portal?

- Figma design file: [HRA Portal Redesign](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=297-1745&mode=design&t=GymmssnTVv4SXDoZ-4)
- Figma prototype presentation: [HRA Portal Redesign (1920x1080)](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=276%3A1145&type=design&node-id=297-1745&viewport=441%2C125%2C0.04&t=XFoSnDpXbJA2kmSC-1&scaling=scale-down&starting-point-node-id=297%3A1745&show-proto-sidebar=1&mode=design)

**Comment by libby-maier** [comment]
Closing this issue as not planned due to being a duplicate, stale, and redesigning this feature. For current issue see #385

**Comment by libby-maier** [comment]
# Ready for development
- Per Katy, 3.6.2024: Move forward with the [original specification](https://github.com/cns-iu/humanatlas.io/issues/232#issue-1794196097) for this feature request from July 2023.
- Closing issue #385 now as not planned
  - Keeping the component in the design system sandbox for further iterations/UIs

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/965cf83a-6cf6-4cf2-b32f-a0224931dce6)

**Comment by libby-maier** [comment]
@bhushankhope - I added the high-priority label to this just now because Katy has been waiting a while for this feature. Let me know if you have any questions!

**Comment by bherr2** [comment]
GRLC link: https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/ccf/#/default/get_as_per_organ

**Comment by bhushankhope** [comment]
@libby-maier I have added the table in PR #408 , currently we only have data for the latest version, let me know if anything needs to change. Thanks.

**Comment by libby-maier** [comment]
Looks great! Thanks @bhushankhope!
