### ISSUE TITLE
Add download column to ASCT+B table on ASCT+B Table page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#236]
# Add download column to ASCT+B table on ASCT+B Table page

### User story: As a user, I want direct access to downloading specific ASCT+B tables, so that I can quickly use them for my research.

The ASCT+B Table page needs an additional column so users can download specific tables directly from the display table. This improves the user experience of downloading specific ASCT+B tables. This column needs to be left aligned. This is part of an ongoing effort to unify the user experiences of our data tables on the HRA Portal.

**Note:** Mock data is used in the prototype and the real ASCT+B table data needs to be used. The official tables need to be sourced for download.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/17cec50a-6eea-4264-bf6e-cb3843801f04)

## To Do
- [ ] Add a column with .csv and .xlsx links to download respective tables immediately from the display table

## Resources
- [Figma design file: ASCT+B table](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4574-37638&mode=design&t=XMWvYOvhAa4I5GrR-4)

**Comment by bhushankhope** [comment]
Added urls to download CSF files in PR #249

**Comment by libby-maier** [comment]
@bhushankhope & @emquardokus - Do we have XLSX files for these ASCT+B tables? We initially specified that we would have both in the Download column. Please let me know if this is possible! Thanks, and happy Friday!

**Comment by bherr2** [comment]
We do not have XLSX files for the ASCT+B tables.

**Comment by libby-maier** [comment]
Thank you, @bherr2! This has been completed, so I am closing this issue.
