### ISSUE TITLE
Add organ icon download section to 2D/3D pages

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#239]
# Add organ icon download section to 2D/3D pages

Users need access to download our organ icons from their GitHub repository. Katy requests new sections on the 2D and 3D pages, linking users to the organ icon GitHub repository: 
> https://github.com/cns-iu/md-icons/tree/main/other-icons/organs

This will be a simple section with a header, a short blurb, and a regular button, which links to the GitHub repository.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/cf794da9-aa25-4187-ab0d-b626aaa5acea)

## To Do

- [ ] Add a section for downloading the organ icons on the 2D page.
- [ ] Add a section for downloading the organ icons on the 3D page.

## Resources
- [Figma design file: 2D page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4590-38172&mode=design&t=XMWvYOvhAa4I5GrR-4)
- [Figma design file: 3D page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4590-38073&mode=design&t=XMWvYOvhAa4I5GrR-4)
- [HRA Organ Icons GitHub Repo](https://github.com/cns-iu/md-icons/tree/main/other-icons/organs)

## Relevant Communication
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/b4950560-c8d3-463c-a3c5-8d0cb0918bf5)

**Comment by bhushankhope** [comment]
Completed this in PR #240

**Comment by libby-maier** [comment]
@bhushankhope, I made a typo in the original request. 

Could you please use a lowercase "o" for organs? Apologies for the silly typo! 

As soon as this is fixed, I will close this issue. Please see below:
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/fd086356-73cf-4e1c-9adc-0e3738bc33e7)

**Comment by libby-maier** [comment]
Thanks so much, @bhushankhope!
