### ISSUE TITLE
Add emojis to Release Notes and Warning banners

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#25]
# Add emojis to Release Notes and Warning banners

Link to Figma design file: https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=325%3A5072&t=rPToXndyvlJWFde0-4

![image](https://user-images.githubusercontent.com/97060856/208167925-a41b25a2-cca2-4b3e-a640-314ecc299137.png)

### 4th Release Notes 
![Party Popper](https://user-images.githubusercontent.com/97060856/208167674-90d44b65-0dda-4667-ae8c-9d86d83f6780.svg)

### Warning
![Warning](https://user-images.githubusercontent.com/97060856/208167846-7645e6e1-ce39-46aa-9d4a-2a9333f74d1c.svg)

**Comment by emquardokus** [comment]
Unicode for warning icon is U+26A0
Unicode for celebration icon U+1F389

**Comment by bherr2** [comment]
Those didn't quite work before, but we can try again. I'm sure it can get done, just wasn't able to get by today.
