### ISSUE TITLE
revise tile of the "ASCT+B table for Lung v1.2" page

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#251]
On the following page, the title should be “Lung v1.3” instead of “Lung v1.2”.
https://hubmapconsortium.github.io/ccf-releases/v1.4/docs/asct-b/asct-b-vh-lung.html

![Screenshot 1](https://github.com/cns-iu/humanatlas.io/assets/133912130/f592d39c-4c09-42be-9131-9b35b4107a15)

**Comment by emquardokus** [comment]
@jianghuayu007 edited and part of pull request: https://github.com/hubmapconsortium/ccf-releases/pull/46
