### ISSUE TITLE
wrong format of " ASCT+B table for Spinal Cord, v1.0" page

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#252]
The" ASCT+B table for Spinal Cord, v1.0" page needs to be reformatted.
https://hubmapconsortium.github.io/ccf-releases/v1.4/docs/asct-b/asct-b-vh-spinal-cord.html 

![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/56cd09a1-c3da-4df6-b4f2-c101ba123dd1)

**Comment by emquardokus** [comment]
@jianghuayu007 there is a pull request already initiated in ccf-releases github from 2 weeks ago; no one has merged it and I can't
@bhushankhope please merge : https://github.com/hubmapconsortium/ccf-releases/pull/46  Update asct-b-vh-spinal-cord.md #46
