### ISSUE TITLE
update the links for organs in ASCT+B Tables

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#253]
In the following webpage (and webpages of all the other organs in the ASCT+B table), when you click the link "" ASCT+B table for Spinal Cord, v1.0" page" in the "Description" part, you will be lead to the old CCF Portal, where the release version is only up to the 3rd release.

ASCT+B table for Blood/Pelvis v1.3: https://hubmapconsortium.github.io/ccf-releases/v1.4/docs/asct-b/asct-b-vh-blood-pelvis.html 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/0e568f24-3dd2-4ffa-8327-964f2e950f48)

The old CCF Portal page: https://hubmapconsortium.github.io/ccf/pages/ccf-anatomical-structures.html 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/b9c0e2ae-662a-43e3-8778-8cdd9a3b70dd)

**Please check the links for all the organs in the ASCT+B table!**
https://humanatlas.io/asctb-tables 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/45444fa5-c909-4e4f-adaa-ef7847910845)

**Comment by bhushankhope** [comment]
Fixed this in PR https://github.com/hubmapconsortium/ccf-releases/pull/47
