### ISSUE TITLE
column titles not shown in the Peripheral_Nervous_System_v1.0 table

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#254]
In the "Peripheral_Nervous_System_v1.0" table, The column tiles are not shown (row 11).
https://docs.google.com/spreadsheets/d/1KifiEDn3PpJ8pjz9_ka4TWkT085wLIzIQP5NKSvb2Ac/edit#gid=714133140 

![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/6056c176-2e2a-4951-9a00-9146dbf8bcbd)

**Comment by bherr2** [comment]
@emquardokus still looks wonky
