### ISSUE TITLE
Update the links for 3D Reference Organs

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#255]
In the following webpage (and webpages of all the other 3D reference organs), when you click the link "This reference organ" in the "Description" part, you will be lead to the old CCF Portal, where the release version is only up to the 3rd release.

3D Reference Organ for Brain, Female v1.2: https://hubmapconsortium.github.io/ccf-releases/v1.3/docs/ref-organs/brain-female.html 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/aa104f3a-5798-41bb-ab67-077d99007c29)

The old CCF Portal page: https://hubmapconsortium.github.io/ccf/pages/ccf-anatomical-structures.html
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/4d76bd1f-bb8a-4c3c-a0e0-62ee1b11f193)

### Check Metadata links for all the 3D reference organs!
https://humanatlas.io/3d-reference-library 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/abdb5ed1-7e9f-41c4-b5ae-7a2960faa0ee)

**Comment by emquardokus** [comment]
@jianghuayu007 I'm not sure what you are expecting to see here.  The version numbers of the organs are NOT identical to the HRA release version.  These are correct. Please let me know.

**Comment by jianghuayu007** [comment]
@emquardokus The version numbers of the 3D organs are correct. But on the "[3D Reference Object Library](https://humanatlas.io/3d-reference-library)" webpage, when you click on the "Metadata" button for the 3D organs and go to the [organ-specific webpage](https://hubmapconsortium.github.io/ccf-releases/v1.3/docs/ref-organs/brain-female.html), and then click the "This reference organ" link in the "Description", it will lead you to the old "[CCF 3D Reference Object Library](https://hubmapconsortium.github.io/ccf/pages/ccf-3d-reference-library.html)" page, where the table of 3D organs is not up to date (see screenshot below). 
It is the same "direct to the old CCF portal" issue as for [ issue #253](https://github.com/cns-iu/humanatlas.io/issues/253). 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/4ce9f677-914d-433d-ba49-a44966879758)

**Comment by bhushankhope** [comment]
Fixed this in PR https://github.com/hubmapconsortium/ccf-releases/pull/47
