### ISSUE TITLE
Update the links in "FAQs for OMAPs" webpage

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#256]
In the "Frequently Asked Questions (FAQs) for Organ Mapping Antibody Panels (OMAPs)" page, when you click the links in the questions "How do I cite an existing OMAP?" and "How do I report imaging methods that employ oligo-conjugated antibodies and fluorescent reporters for marker detection?", you will be lead to the old  CCF Portal, where the release version is only up to the 3rd release.

FAQs for OMAPs: https://humanatlas.io/faq/omap 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/0c1d0d6c-aa46-4deb-ab4e-988bd7e30f47)
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/6094410a-cc1d-47f2-8513-3841bada045d)

The old CCF Portal page: https://hubmapconsortium.github.io/ccf/pages/omap.html 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/c55ef3a4-7934-4954-ba0b-acbbbdad448f)

**Comment by emquardokus** [comment]
@jianghuayu007 yes, I was originally told that the old CCF portal would redirect to the hra portal, but it doesn't and the HRA portal did not yet exist when we published.  I'm already working on updates across OMAP, AVR and both SOPs.

**Comment by bhushankhope** [comment]
Fixed this in PR #270
