### ISSUE TITLE
Update link and improve format on "Preview: HRA vs. Experimental Data" webpage

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#259]
### ISSUE 1:
In the "[Preview: HRA vs. Experimental Data](https://hubmapconsortium.github.io/hra-previews/pilots/pilot3.html)" page, the link "lookup table" in the "Description" part leads to a wrong path in the GitHub repository.

Preview: HRA vs. Experimental Data: https://hubmapconsortium.github.io/hra-previews/pilots/pilot3.html 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/7b6123ec-e063-4660-8cf8-6218721f30f9)

Wrong link: https://github.com/hubmapconsortium/azimuth-annotate/blob/main/data/kidney.json 
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/b5b0df09-b09f-48e3-ae5e-5cd1e4ccc88e)

### ISSUE 2:
The format in the "Attribution" part needs to be improved.
![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/59f84754-ed49-475c-b667-c3158ff4df01)

**Comment by bhushankhope** [comment]
I have fixed this.
