### ISSUE TITLE
Update carousel picture ASAP

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#260]
The carousel's first slide needs to use the following picture:

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/3f5c8918-77bc-4672-bca6-16341644fa9d)

Katy requests this be completed with urgency. Thank you!

## Resources
- [Figma design file: New carousel image](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4667-14695&mode=design&t=tA4Ma4yGr3dBAUaA-4)

**Comment by bhushankhope** [comment]
Updated the slide in PR #262

**Comment by libby-maier** [comment]
Amazing, thanks for the quick work @bhushankhope!
