### ISSUE TITLE
Update: Added link for representative data set for OMAP-3 kidney to omaps_release5_rep_data.csv 

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#261]
Added link for representative data set for OMAP-3 kidney to omaps_release5_rep_data.csv below:

[omaps_release5_rep_data.csv](https://github.com/cns-iu/humanatlas.io/files/12185955/omaps_release5_rep_data.csv)

**Comment by bhushankhope** [comment]
Added this in PR #263
