### ISSUE TITLE
Add HRA Diversity section to 5th Release Notes page & table of contents menu

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#264]
# Add HRA Diversity section to 5th Release Notes page & table of contents menu

Diversity information has been added to the [5th Release Notes page](https://humanatlas.io/release-notes/v1.4). Please note that this is a high-priority request. Thank you!

## To Do
- [ ] Add "HRA Diversity" as a menu item in the Table of Contents menu between What's New and ASCT+B Reporter & OMAP Support.
- [ ] Add HRA Diversity content between What's New and ASCT+B Reporter & OMAP Support.

## Resources
- [Google Doc: HRA Diversity](https://docs.google.com/document/d/1QKKpC0ewZriBu4JcQz4NNStmYRHiIdzlB94pYmQ5SaA/edit)
- [Figma design file: Table of Contents menu for 5th Release Notes](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4289-35402&mode=design&t=Cy4sSvAx2rb7H5cm-4)
- [Figma design file: HRA Diversity section](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=4689-14392&mode=design&t=Cy4sSvAx2rb7H5cm-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/85869689-37bb-48e7-b056-68a81f501e42)

**Comment by bhushankhope** [comment]
Completed this in PR #265

**Comment by libby-maier** [comment]
@bhushankhope Thanks so much!
