### ISSUE TITLE
Remove all the unnecessary files from the code

### ISSUE THREAD

**Issue by bhushankhope** [cns-iu/humanatlas.io#267]
Remove the following things from the code
- All the folders under the pages folder
- All the SVG, AI, PNG files under the assets folder

**Comment by bherr2** [comment]
You missed one: https://github.com/cns-iu/humanatlas.io/tree/develop/src/app/pages/tissue-info-page :-)

**Comment by bhushankhope** [comment]
Completed this in PR #269 and PR #292
