### ISSUE TITLE
Revise content on the "ASCT+B Cell-Types Data from Azimuth Reference Data with Summaries" page

### ISSUE THREAD

**Issue by jianghuayu007** [cns-iu/humanatlas.io#271]
On the "[ASCT+B Cell-Types Data from Azimuth Reference Data with Summaries](https://humanatlas.io/asctb-azimuth)" page, there are "Table 1" and "Table 3" mentioned in the content. However, there is only one table shown on this webpage.

![image](https://github.com/cns-iu/humanatlas.io/assets/133912130/e56dc581-9569-4467-8642-f4a727c6351f)

**Comment by libby-maier** [comment]
This content has been updated. Please use the [Figma design file's Azimuth page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-17676&mode=design&t=N0Uc1DijkUHiOIJh-4) for the source of truth for these minor content updates.

Minor verbiage and embedded link updates occurred in the following sections:
- Overview
- Azimuth Cell-Type Typologies and Counts
- Comparison of CxG in ASCT+B vs. Azimuth
- Azimuth CT Counts

These sections are unchanged:
- Terms of Use
- References

Thank you!

**Comment by bhushankhope** [comment]
Fixed this in PR #364

**Comment by libby-maier** [comment]
Thank you, @bhushankhope - Noting this as completed.
