### ISSUE TITLE
Update 2D FTU table at bottom of page; mappings and typos

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#279]
Update the ontology mapping of 4 items in ftu-cell-count-5th-release.csv 
Discussed with @bherr2 with his need for lookup table for interactive FTU; found some mismapped FTU.

- [ ] Typo found Dermal Pappila should be Dermal Papilla UBERON:0001992
- [ ] Replace ftu-cell-count-5th-release.csv  with attached file
[ftu-cell-count-5th-release.csv](https://github.com/cns-iu/humanatlas.io/files/12303781/ftu-cell-count-5th-release.csv)

Dermal Papilla  maps to UBERON:0001992 papillary layer of dermis replaced: dermis UBERON:0002067

Prostate glandular acinus maps to UBERON:0004179	prostate glandular acinus replaced: prostate gland stroma UBERON:0004184

Crypt of Lieberkuhn maps to UBERON:0001984 crypt of Lieberkuhn of large intestine replaced: UBERON:0011184 epithelium of crypt of Lieberkuhn

Epidermal Ridge maps to UBERON:0013487 epidermal ridge of digit replaced:  UBERON:0001003 skin epidermis

**Comment by bhushankhope** [comment]
Updated the csv. It fixed the typo. 
#280
