### ISSUE TITLE
boppana link broken on vccf page

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#281]
https://cns.iu.edu/docs/publications/2022-Boppana_ASCT+B.pdf does not exist. @libby-maier can you track down where this is so @bhushankhope can update?

**Comment by mtgallant** [comment]
The link name may be incorrect.  use "2023-Boppana_ASCT+Bs.pdf"

**Comment by bherr2** [comment]
Yes, https://cns.iu.edu/docs/publications/2023-Boppana_ASCT+Bs.pdf looks like the right link

**Comment by bhushankhope** [comment]
Fixed this in PR #291
