### ISSUE TITLE
Missing missing a test alternative 

### ISSUE THREAD

**Issue by mtgallant** [cns-iu/humanatlas.io#282]
Https://humanatlas.io/ has 13 mages that do not have text alternatives 
/assets/images/hubmap_dude.svg
/assets/images/carousel1.svg
/assets/images/carousel3.svg
/assets/images/carousel6.svg
/assets/images/consortia.svg
/assets/images/experts.svg
/assets/images/publications.svg
/assets/images/organs_metric.svg
/assets/images/biomarkers.svg
/assets/images/anatomical-structures.svg
/assets/images/cell-types.svg
/assets/images/omap.svg
/assets/images/ftu.svg

**Comment by bhushankhope** [comment]
Added alt to images in PR #287

**Comment by bhushankhope** [comment]
added alt text to all images in PR #329
