### ISSUE TITLE
SiteImprove color contrast

### ISSUE THREAD

**Issue by mtgallant** [cns-iu/humanatlas.io#284]
siteimprove lists color contrast issue with:
Data
Contrast ratio
 = 5.28:1
This item may not be visible on the page. Switch to HTML view to see it highlighted in the code.
Issue location
Switch to HTML view to display exact element location
Increase the contrast ratio to 7:1 or higher.
Result

Contrast ratio: 5.28:1
Color details
Color contrast requirements vary depending on WCAG conformance level and font size.

Text color:
#0A6EBD / RGB (10, 110, 189)

Background color:
#FFFFFF / RGB (255, 255, 255)

Occurrence details:CCF Ontology
Contrast ratio
 = 5.28:1
This item may not be visible on the page. Switch to HTML view to see it highlighted in the code.
Issue location
Switch to HTML view to display exact element location
Increase the contrast ratio to 7:1 or higher.
Result

Contrast ratio: 5.28:1
Color details
Color contrast requirements vary depending on WCAG conformance level and font size.

Text color:
#0A6EBD / RGB (10, 110, 189)

Background color:
#FFFFFF / RGB (255, 255, 255)

Occurrence details:Tools
Contrast ratio
 = 5.28:1
This item may not be visible on the page. Switch to HTML view to see it highlighted in the code.
Issue location
Switch to HTML view to display exact element location
Increase the contrast ratio to 7:1 or higher.
Result

Contrast ratio: 5.28:1
Color details
Color contrast requirements vary depending on WCAG conformance level and font size.

Text color:
#0A6EBD / RGB (10, 110, 189)

Background color:
#FFFFFF / RGB (255, 255, 255)

Occurrence details:Training and Outreach
Contrast ratio
 = 5.28:1

**Comment by bherr2** [comment]
@libby-maier please review and come back with recommendations.

**Comment by libby-maier** [comment]
Hi @bherr2,

Please use #054F89 for ready in-text links.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/c6ecd253-228c-4412-af96-afeb2cf628b1)

**Comment by bherr2** [comment]
You mean @bhushankhope  ?

**Comment by bhushankhope** [comment]
fixed this in PR #286
