### ISSUE TITLE
SiteImprove line-height set to 1.5

### ISSUE THREAD

**Issue by mtgallant** [cns-iu/humanatlas.io#285]
SiteImprove accessibility for humanatlas.io 
- between 17 and consortia
- between 250+ and experts
- between 1,000+ and publications
- between 66 and organs
- between 4,279 and anatomical structures
- between1,209 and cell types
- between 2,089 and biomarkers
- between 13 and organ mapping antibody panels
- between 21 and functional tissue units
- between Data and Research the data constructing the Human Reference Atlas

**Comment by libby-maier** [comment]
## Text styles have been updated in Figma to support a line height of 1.5:
- Subtitles
- Small UI Text (formerly called Organ Icon Button)

See the Figma design file: [Metrics component](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-16299&mode=design&t=N0Uc1DijkUHiOIJh-4)


![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/14556f96-2d34-4cbc-b16c-616161433eec)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/58460b14-8750-460f-975f-54d1a212d5f0)

## Body text style added to the animated card component on the home page to support a line height of 1.5:
- Figma design file: [Animated card components](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-16357&mode=design&t=N0Uc1DijkUHiOIJh-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/154c7b71-0cd5-4a20-8ff9-063bc72fd59b)

**Comment by bhushankhope** [comment]
Fixed this in PR #383
