### ISSUE TITLE
Update breast icon button to mammary gland icon button

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#29]
The breast icon button needs to be updated to Mammary Gland for the 3D Reference Object page. 

### SVGs

ready state:
![Organ=Mammary Gland, State=Ready](https://user-images.githubusercontent.com/97060856/208194022-dd80313b-56d6-491c-b41a-6a4970f069a7.svg)

hover state:
![Organ=Mammary Gland, State=Hover](https://user-images.githubusercontent.com/97060856/208194019-add03c4c-d4e1-46e8-816c-2d4a0df19a73.svg)

selected state: 
![Organ=Mammary Gland, State=Selected](https://user-images.githubusercontent.com/97060856/208194023-9ef65a3c-5617-4b97-82cd-e7b31d4d2d25.svg)

### Figma design node
organ button component: https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=532%3A9051&t=rPToXndyvlJWFde0-4

**Comment by emquardokus** [comment]
@bherr2 @bhushankhope Libby and I noticed that the icon for "breast" appears on the 3D model page, but in RUI it's mammary gland.  It's in the correct location in terms of alphabetically as though it is called mammary gland, just need to update the text in the carousel.
