### ISSUE TITLE
Upgrade to Angular 16

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#290]
Please update all dependencies, including Angular to latest version. This project will likely be merged into the monorepo ([hra-ui](https://github.com/hubmapconsortium/hra-ui)) and all other applications are being updated to Angular 16 in preparation.

**Comment by bherr2** [comment]
Doesn't have to be done immediately if there are other high priority things to do. We want this updated by end of August, ideally, but mid-September at latest.

**Comment by bhushankhope** [comment]
Completed this in PR #309
