### ISSUE TITLE
ADD recent developer name / photo to ASCT+B reporter Pramod Bhakta

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#294]
Add name and photo to https://hubmapconsortium.github.io/ccf-asct-reporter/ at bottom of page with contributors. 

Photo and information from https://cns.iu.edu/previous_team.html

![](https://cns.iu.edu/images/people/pramod-bhakta.png)
Pramod Bhakta
Angular Developer
pnbhakta@iu.edu
2022.05.15 - 2023.08.04

**Comment by bhushankhope** [comment]
Added this in PR https://github.com/hubmapconsortium/ccf-asct-reporter/pull/739

**Comment by emquardokus** [comment]
Thanks!
