### ISSUE TITLE
Small content updates for 5th Release Notes page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#305]
# Small content updates for 5th Release Notes page

### 1
- [x] Katy and Bruce's images on the 5th Release Notes page would not load on Katy's Mozilla Firebox browser today during a meeting. Can you please ensure these images load on all browsers?
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/76b5c7a7-2a80-4d1d-a0bc-8519a6a907ae)

### 2
- [x] The last image on the page needs to be updated to the same image used in the carousel. Use the following image:
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/2b60a7fb-692a-41ea-b37e-e5df950dd014)

### 3
- [x] Andreas Bueckle's job title and photo need to be updated. His job title will be updated to Research Lead. [View the new image in Figma](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas---v1.3-%26-v1.4?type=design&node-id=3078-11335&mode=design&t=omYkEt45KDCHdUXp-4).

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/21bc919f-ec62-4132-8412-995fdcb6b0c2)

### 4
- [x] Update Bruce's title to Technical Director
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/466185a3-5f0c-4e17-8e3d-b8df3b38e257)

**Comment by bhushankhope** [comment]
Updated content in PR #306

**Comment by libby-maier** [comment]
Hi, @bhushankhope 

Most of the updates look good, but Andi's title needs to be updated to Research Lead. Thanks so much!

**Comment by bhushankhope** [comment]
@libby-maier Fixed job title in PR #307
