### ISSUE TITLE
Update text content for Human Atlas Stories

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#311]
Katy & Todd updated the content for Human Atlas Stories preview page.

- [ ] Update [Human Atlas Stories page](https://hubmapconsortium.github.io/hra-previews/pilots/pilot4.html) with content from [Google Doc: Human Atlas Stories](https://docs.google.com/document/d/10aPX_6Vca8-GYJ532C8V5YDVnQbyW3eRjLQTvzYS2tA/edit#heading=h.iq9tifabyaac)

Thanks so much!

**Comment by bhushankhope** [comment]
Completed in PR https://github.com/hubmapconsortium/hra-previews/pull/13
@libby-maier

**Comment by libby-maier** [comment]
Thank you @bhushankhope!
