### ISSUE TITLE
Update text for Kaggle 2 Page to add code and publication

### ISSUE THREAD

**Issue by J-Yash** [cns-iu/humanatlas.io#313]
Update the text on the Kaggle 2 page (https://humanatlas.io/kaggle-two) based on the **suggested edits** in this document (https://docs.google.com/document/d/15bIdi7X1zPCK5aaU_1wNbw8A5G4NhlM5jmQdq_T7xcM/edit?usp=sharing)

TODO:

- [x] Add "Publication" section containing link to published paper and citation.
- [x] Add "Code" section containing link to GitHub repo.
- [x] Minor text edit for "Data" section.

**Comment by bhushankhope** [comment]
Completed above tasks in PR #316 . Please review @J-Yash

**Comment by J-Yash** [comment]
Reviewed. Closing issue.
