### ISSUE TITLE
Add disclaimer to footer 

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#315]
**Medical Disclaimer: This resource is intended for research purposes only. It should not be used for emergencies or medical or professional advice.**

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/2e4fb2f4-cb2d-4125-91f2-5c659057e36b)

**Comment by libby-maier** [comment]
# Add medical disclaimer text to the footer

A medical disclaimer has been added to the footer to be visible on all pages. The same responsive functionality of the current footer is needed for this text.

- [ ] Add the medical disclaimer to the footer component, ensuring that the spacing and verbiage are as specified.
> Medical Disclaimer: This resource is intended for research purposes only. It should not be used for emergencies or medical or professional advice.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/95f2f7f8-7a90-4b40-8772-19259f02910c)

## Resources
- [Figma design file: 6th Release Footer](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4812-47449&mode=design&t=L5R6WlK7QDLglIQs-4)
- [Figma design file: 6th Release HRA Portal page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-14394&mode=design)

**Comment by bhushankhope** [comment]
added this in PR #327 #328

**Comment by libby-maier** [comment]
Thanks @bhushankhope!
