### ISSUE TITLE
Design interaction to Digital Object listing

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#322]
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/438baf62-e1f3-4a26-9dcd-10f77f9970ab)

**Comment by bherr2** [comment]
Use the CDN link though: https://cdn.humanatlas.io/ccf-releases/v1.4/docs/index.html

**Comment by bherr2** [comment]
Strike that, actually https://cdn.humanatlas.io/hra-releases/v1.4/docs/index.html :-)

**Comment by libby-maier** [comment]
Thanks @bherr2! Will there be a different URL for 6th (v1.5)?

**Comment by bherr2** [comment]
Same base url, but the version may be different (either v2.0 OR v6 😮)

**Comment by libby-maier** [comment]
Hi @bherr2, are there any updates for this URL for the 6th Release? I am starting the 6th release content notes today - Wanted to confirm. Thank you!

**Comment by bherr2** [comment]
No changes, but still finalizing what the version number will actually be. You can stick with v1.5 in the interim.

**Comment by libby-maier** [comment]
### Design to do's:
- [ ] Design interaction from the data overview page.
- [ ] Design interaction from the 6th release notes page.

**Comment by libby-maier** [comment]
Hi @bherr2,

Will the link for this content be  https://cdn.humanatlas.io/hra-releases/v2.0/docs/index.html or https://cdn.humanatlas.io/hra-releases/v6/docs/index.html?

Looking forward to finalizing this in the prototype. Thank you!

**Comment by bherr2** [comment]
v2.0

**Comment by libby-maier** [comment]
Perfect, thank you! I have what I need. Closing this out now.
