### ISSUE TITLE
Restructure navigation for 6th release and feature use cases 1-3 prominently

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#323]
## Initial design to do's
- [x] Adding use cases call to action link on the 6th release notes card. 
- [x] Create 3 documents for Use Case 1-3, send to Katy, Andi, Bruce
- [x] Add documents to HRA Content Tracker
- [x] Navigation dropdown for use cases replacing CCF Ontology. 
- [x] Remove CCF ontology from main navigation and move to Data
- [x] Create a use case overview page. 
- [x] Obtain content from Katy, Bruce, and Andi. Titles, subtitles, and page content are needed to fulfill the milestone.
- [x] Pass 4 new pages for the HRA Portal to development (User Stories Overview, US1-3). Note that the video content will come later.

## Resources:
- [Google Doc: CNS UX Specs - 10/4](https://docs.google.com/document/d/1b6lkC87DALStq-_WHQrvxr3fs_i5XEas-4MfN_-zw1k/edit#heading=h.rb50ljcs0mor)
- [Figma design file: 6th Release](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-14394&mode=design)
- [HRA Content Tracker](https://docs.google.com/spreadsheets/d/1t4OOVgushmZQaDdnvv5ShqwKc-m8SUrwRbYNkQ-rxq4/edit#gid=245916554)
- [Google Drive folder: Use Case 6th](https://drive.google.com/drive/folders/1F7JIQ-H4z5Y_PnvTO-ruyN_xzsEVyl3h?usp=drive_link)

**Comment by libby-maier** [comment]
# Restructure navigation for 6th release and feature use cases 1-3 prominently

Navigation has been modified and four pages have been added to the HRA Portal. The CCF Ontology page has been categorized as a Data item, moving it into the Data menu and Data Overview page.

## Notes for the development team:
- Figma acts as the source of truth for the content within this issue.
- Links go to the respective Figma design file nodes below.
- Currently, on the new User Stories pages, placeholder boxes remain for what will eventually be embedded YouTube videos. Please note that we will embed a YouTube video on each of these pages before the 6th Release on December 15th.

## Implementation To Do's:
- [ ] [Navigation bar](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4834-17802&mode=design&t=SpxyWsm9wnJRlgzG-4): Move CCF Ontology to the Data menu in the navigation bar.
- [ ] [Data Overview](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-17287&mode=design&t=SpxyWsm9wnJRlgzG-4): Add CCF Ontology card button to the Data Overview page.
- [ ] [Navigation bar](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-16505&mode=design&t=SpxyWsm9wnJRlgzG-4): Add a new dropdown option titled "Use the HRA" in place of the former CCF Ontology listing.
- [ ] [Navigation bar](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4834-14524&mode=design&t=SpxyWsm9wnJRlgzG-4): Add a dropdown menu linking to the Overview page and to each user story page.
- [ ] [Overview: Use the HRA page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4835-17823&mode=design&t=SpxyWsm9wnJRlgzG-4): Implement the new Use the HRA Overview page.
- [ ] [User Story 1 page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4842-29440&mode=design&t=SpxyWsm9wnJRlgzG-4): Implement the new page Improve Cell Type Annotations.
- [ ] [User Story 2 page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4842-29984&mode=design&t=SpxyWsm9wnJRlgzG-4): Implement the new page Predict 3D Spatial Origin of Tissue Samples
- [ ] [User Story 3 page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4842-30352&mode=design&t=SpxyWsm9wnJRlgzG-4): Implement the new page Explore Biomarker Expressions for Cell Types

**Comment by bhushankhope** [comment]
@libby-maier  I have implemented these changes. You can review them here
https://humanatlas-io.netlify.app/

**Comment by libby-maier** [comment]
Hi @bhushankhope, it's looking great. 

The only issue I see right now is that this image for US3 needs to expand out to the whole page. Is it possible to get this closer to the specification? The image should expand to its full size responsively. Also, this image will be changing, so I'll submit an issue as soon as it needs to be updated.

Use the file below, located in the [UI Annotations Figma File](https://www.figma.com/file/GIKR3xb5vAUgaEuxloZwpM/UI-Annotations?type=design&node-id=78-3&mode=design&t=MRw1EJOCjCX7rL2V-4).
![FTU Explorer Annotation](https://github.com/cns-iu/humanatlas.io/assets/97060856/9f0a6ca3-5485-4c4e-bba6-1f7f57143c37)
n?

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/87e2789a-cc5a-4bb0-89f4-9d71b152bfe3)

**Comment by libby-maier** [comment]
Adding Katy's example of the responsive 4K visual functionality we want to achieve with the annotation graphic
- https://opencell.czbiohub.org/help

**Comment by libby-maier** [comment]
Bhushan and I have been working together on this issue for user story 3. See the [Figma design file](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5254-8524&mode=design&t=qBLdFthL6p88jmXK-4) for the updated mockup.

# New UI:
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/bcef3b99-10d0-4f69-bf9f-0e8ef32e36de)

# New Annotation Image
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/e479142c-0db2-43e9-8218-8c1e10f3cbb8)

**Comment by libby-maier** [comment]
@bhushankhope & @bherr2 -

The navigation and pages all look great but we do need to update the videos and the headers for them.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/8af3fd45-33f7-4af9-b225-4ac5f7a14f20)

**Comment by libby-maier** [comment]
Please remove the video demonstration section if we don't have time to make these demo videos happen before December 15th. Thanks so much for all of your hard work, team!

**Comment by andreasbueckle** [comment]
@libby-maier @bhushankhope 
It was brought to my attention that we need video demos. I assume one for US1 and one for US2? Will YT video IDs links work?

**Comment by bherr2** [comment]
Yep!

**Comment by andreasbueckle** [comment]
HRA US1: https://youtu.be/KuZ_bwLHipM
HRA US2: https://youtu.be/AlcTRCMU2ME

**Comment by bherr2** [comment]
Thanks! Updated and added to staging.

**Comment by libby-maier** [comment]
Hi @bherr2,

@andreasbueckle and I made some significant updates to the EUI annotation visual for US#3 today.

Would it be possible to replace the current annotation with the updated image below?

![EUI Annotation 12 14 2023](https://github.com/cns-iu/humanatlas.io/assets/97060856/7cc775bf-ddc5-40de-b926-634b52ede8d1)

**Comment by bherr2** [comment]
You betcha, just added to develop <https://github.com/cns-iu/humanatlas.io/commit/d292866b8a3af70c4237961b8e0e89f8d00819d9>

**Comment by libby-maier** [comment]
Thank you so much @bherr2! It appears squished from a random Google Chrome browser window size on my big home monitor. It looks fine when my browser is set to full screen. Is it possible to prevent it from looking squished?

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/4ae6bd94-81cb-4529-b1a7-7d6fbeb5bcf0)

**Comment by bherr2** [comment]
I'll have daniel or ed look at it

**Comment by libby-maier** [comment]
Excellent, thank you so much!

**Comment by axdanbol** [comment]
Image squishing fixed by #377

**Comment by libby-maier** [comment]
Thank you so much team!
