### ISSUE TITLE
Rename omaps_release5_rep_data.csv to omaps_release5.csv

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#330]
@bhushankhope I was talking to Bruce about a different issue when it came to our attention this morning that the https://github.com/cns-iu/humanatlas.io/tree/main/apps/ccf/src/assets/table-data has two files for 5th release for OMAPs...there should only be one. 

<img width="852" alt="Screenshot 2023-11-01 at 12 11 32 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/7ed2c1f3-c725-4e7d-a702-cc1010ae6142">

The correct file is omaps_release5_rep_data.csv but should be renamed to **omaps_release5.csv** to replace the previous one that existed which is old.

[omaps_release5_rep_data.csv](https://github.com/cns-iu/humanatlas.io/files/12185955/omaps_release5_rep_data.csv)

**Comment by bhushankhope** [comment]
Fixed this in PR #331
