### ISSUE TITLE
6th Release Notes page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#333]
# Design to do's
- [x] Finalize content for the 6th release notes page in [Google docs](https://docs.google.com/document/d/17F_oQ4e6h_N1pZKTzBqGhNNRCVhOzHGSjvo45arLnxA/edit#heading=h.187laarduava).
- [x] [Finalize design in Figma](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4842-29236&mode=design&t=7XPUE6ISjfko0KM6-4).

Note for @bhushankhope: The structure of this page will be exactly the same as the live pages for 4th release notes & 5th release notes. We will add a card button to the Training & Outreach overview page per usual. [See Figma for Training & Outreach Overview](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-17396&mode=design&t=IgJImyDwvdo1uZha-4).

**Comment by libby-maier** [comment]
### Notes for @bhushankhope 

- I reached out to Lisel and Katy to finalize this content today as it is due by the end of the business day.
- I don't have time to style the underlined embedded links in the design file. There are no changes to the embedded link look and functionality from the standard around the HRA Portal. We will use the same styling for embedded, in-text links; all external links should open in new tabs per usual. Thank you!

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/17466b81-0854-4d7e-ad2b-c50c65448a7d)


![F928A6F6-B785-454E-B441-D29F2012B2C6](https://github.com/cns-iu/humanatlas.io/assets/97060856/5f732711-03b3-47b6-b6eb-4d32549707a7)

**Comment by libby-maier** [comment]
Afternoon update: Content is finalized and passed off to Katy for review. 

We will use this content if we don't hear back by noon tomorrow.

**Comment by libby-maier** [comment]
6th Release Notes content has been finalized in the [Google Doc](https://docs.google.com/document/d/17F_oQ4e6h_N1pZKTzBqGhNNRCVhOzHGSjvo45arLnxA/edit#heading=h.187laarduava). Thanks so much!

**Comment by libby-maier** [comment]
Hi @bhushankhope - Katy and Andi added several last-minute changes in the [Google Doc](https://docs.google.com/document/d/17F_oQ4e6h_N1pZKTzBqGhNNRCVhOzHGSjvo45arLnxA/edit#heading=h.187laarduava). Most of the content was updated and 3 new sections were updated as well. Please use this document as the source of truth as Figma will not be updated tonight. I will be in at 9 am tomorrow. Let me know if you have questions, and thanks for all of your work on CNS websites!

**Comment by libby-maier** [comment]
One last update for the SOPs section this morning:

- [SOP: Computing Cell Type to Vasculature Distance Distributions](https://zenodo.org/doi/10.5281/zenodo.10371472)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/e6e8a7b3-2d3f-4ed8-821b-1b74e6f2e671)

**Comment by bhushankhope** [comment]
Added this in PR #368

**Comment by libby-maier** [comment]
## Morning Staging Review:
It's looking great @bhushankhope! I found a few items that need to be edited for this page:
- [ ] APIs & Interfaces section: Embed the [FTU Explorer link](https://hubmapconsortium.github.io/hra-ui/apps/ftu-ui/).
- [ ] Use the HRA section: The bulleted list needs to route to their respective Use the HRA page/user story page. Currently, they all route to humanatlas.io's landing page.
- [ ] Contact Us section: All mailto: links route to Katy's email. Please add Bruce & Andreas' emails to their respective cards.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/4923f62f-a85c-40d4-a89b-9e3b0b5dc223)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/27043261-4c74-4168-8915-830ed58d1f9e)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/bf080137-eca7-4d01-bb8f-2b4c0818193e)

**Comment by bhushankhope** [comment]
Fixed this in PR #371
