### ISSUE TITLE
UPDATE:  HuBMAP logo from digital object metadata pages points to the deprecated CCF portal rather than HRA portal

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#336]
I noticed today when clicking on the HuBMAP icon in upper left of pages that display digital object metadata, it points back to the deprecated CCF portal rather than to the HRA portal.
<img width="1018" alt="Screenshot 2023-11-09 at 3 40 23 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/1ae03513-3a60-4edd-b099-ec3ad37e69e1">

This seems to ONLY be a problem on digital object metadata pages which are being pulled from ccf-releases github markdown files. Affects ASCT+B, 2D FTU, 3D model, VCCF, OMAP digital object metadata pages, NOT the landing pages for those.

Likewise, the whole navigation bar is not the same as the rest of the HRA website, I think if it were replaced consistently for all pages, this would be resolved.

Correct navigation bar found on all content pages: 
<img width="991" alt="Screenshot 2023-11-09 at 3 40 09 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/cc3b3b01-961f-4bc7-a1e8-b0179997b9cf">

**Comment by bherr2** [comment]
I'll take this one.

**Comment by bhushankhope** [comment]
fixed by bruce. closing
