### ISSUE TITLE
PURLS for OMAPs have problems with .csv and xlsx going to 404 not found

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#337]
These purls go to "latest" version of OMAP; however, the .csv and xlsx links go to 404 not found.

If you access the OMAPs from individual  release page, the .csv and xlsx links go to the right place.

Not sure how this is working right now to suggest a fix.

OMAP_ID | OMAP Page PURL
-- | --
OMAP-1 | https://purl.humanatlas.io/omap/1-human-lymph-node-ibex
OMAP-2 | https://purl.humanatlas.io/omap/2-intestine-codex
OMAP-3 | https://purl.humanatlas.io/omap/3-kidney-codex
OMAP-4 | https://purl.humanatlas.io/omap/4-skin-cell-dive
OMAP-5 | https://purl.humanatlas.io/omap/5-liver-sims
OMAP-6 | https://purl.humanatlas.io/omap/6-pancreas-codex
OMAP-7 | https://purl.humanatlas.io/omap/7-lung-cell-dive
OMAP-8 | https://purl.humanatlas.io/omap/8-placenta-full-term-imc
OMAP-9 | https://purl.humanatlas.io/omap/9-kidney-codex
OMAP-10 | https://purl.humanatlas.io/omap/10-palatine-tonsil-macsima
OMAP-11 | https://purl.humanatlas.io/omap/11-spleen-ibex
OMAP-12 | https://purl.humanatlas.io/omap/12-eye-retina-ibex
OMAP-13 | https://purl.humanatlas.io/omap/13-pancreas-codex

**Comment by bherr2** [comment]
This needs to be routed to hra-do-processor. And I'll assign myself to it.

**Comment by bherr2** [comment]
Fixed in production
