### ISSUE TITLE
6th release: add small intestine icon to organ selector on 2D FTU page

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#338]
Please add small intestine to the organ selector for 2D FTU.

The new 2D FTU will be intestinal villus

Icons are here:
[https://github.com/cns-iu/md-icons/tree/main/other-icons/organs](https://www.google.com/url?q=https://github.com/cns-iu/md-icons/tree/main/other-icons/organs&sa=D&source=docs&ust=1701189891489834&usg=AOvVaw3I-9N8702mPlY-nFOkBbWD)

 ico-organs-small intestine.svg

**Comment by libby-maier** [comment]
Thank you @emquardokus! 

The [Figma design file 2D FTU page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-14603&mode=design&t=9cuLBmtVH13USBBr-4) has been updated to reflect this new FTU.

I will remove my assignment now as the design work is completed. Thanks so much!

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/148d2349-6215-4437-984f-dfc07ddd98af)

**Comment by bhushankhope** [comment]
Added this in PR #361
