### ISSUE TITLE
6th Release dropdown component updates due on 6th Release day (December 15)

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#339]
## To Do

Update the dropdown for the 6th Release on the following pages:

- [ ] ASCT+B Tables
- [ ] VCCF page
- [ ] 2D FTU Illustrations
- [ ] 3D Reference Object Library 
- [ ] OMAPs

The dropdown behavior is unchanged and defaults to the newest release per usual.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/a3caea7c-32a5-4aab-9dd5-7387dc1f4a48)

## Resources
- Figma design file: [Release options menu 6th](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-16503&mode=design&t=9cuLBmtVH13USBBr-4)
- Figma design file: [Default dropdown](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5198-11305&mode=design&t=9cuLBmtVH13USBBr-4)

**Comment by bhushankhope** [comment]
Added this in PR #343 . Data yet to be added for 6th release.
Currently in develop
