### ISSUE TITLE
2 incorrect links on caurosel

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#345]
The first and second slide buttons on the landing page carousel link to the HuBMAP Data Portal. Only the third slide should link to the Data Portal.

The first slide should link to https://doi.org/10.1038/s41556-021-00788-6
The second slide should link to https://humanatlas.io/asctb-reporter

Figma design file: [Caurosel MVP2](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-17430&mode=design&t=7W2o3fPyIE4lo5Ut-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/ec767d3e-2340-46b6-bb0a-02585c764222)

**Comment by bhushankhope** [comment]
Fixed this in PR #346

**Comment by libby-maier** [comment]
Thank you!
