### ISSUE TITLE
Update landing metrics on 6th Release day on Dec 15th

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#347]
The landing page metrics section will need adjustments to the counts on December 15th.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/cf0e38f5-8495-42ed-aa59-f06961a9874b)

## Relevant Communication
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/5b8bd74a-f9e1-40fd-9ca9-c8b4ed9ace07)

**Comment by bhushankhope** [comment]
Closing this issue
