### ISSUE TITLE
Update HRA SOPs with new links

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#349]
Lisel provided new links to a couple of SOPs for the [SOPs page](https://humanatlas.io/standard-operating-procedures) in [Google Doc: HRA SOPs](https://docs.google.com/document/d/1Q-Fyi1N1uSwFvE4FBpFL9kvylLSbpElxHaYEVvgucNs/edit). More SOPs might be added right before the 6th release. I will add updates on this issue as I receive them. Thank you!

New for 6th:
- [Managing SOPs](https://docs.google.com/document/d/1FNERIQqn8sZVfIaqtg5VKjoTfogmLAVNYIR5mM-4TjE/edit#heading=h.lpsf90jpnlzf)
- [SOP Template](https://docs.google.com/document/d/1LxC74bJqpF7WuuxcensALPnmURcjxmt6DTm7F9xiJDU/edit#heading=h.lpsf90jpnlzf)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/7c9f7a4a-542e-4ee6-9434-4a91c6e65fde)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/f53f7caf-636b-40e3-94ec-07dfc830d456)

**Comment by bhushankhope** [comment]
Added them in PR #343 . Currently in develop

**Comment by libby-maier** [comment]
Hi @bhushankhope - Lisel has finalized adding additional SOPs to the [SOP Table of Contents doc](https://docs.google.com/document/d/1Q-Fyi1N1uSwFvE4FBpFL9kvylLSbpElxHaYEVvgucNs/edit). She noted which items have changed via the comment function. Please make these updates for the 6th Release. Thank you so much!

**Comment by libby-maier** [comment]
One last edit has been made this morning. This content is now finalized @bhushankhope!

**Comment by bhushankhope** [comment]
Added all edits in PR #363

**Comment by libby-maier** [comment]
One last edit for @bhushankhope in the [SOPs Table of Contents](https://docs.google.com/document/d/1Q-Fyi1N1uSwFvE4FBpFL9kvylLSbpElxHaYEVvgucNs/edit)

- [Computing Cell Type to Vasculature Distance Distributions](https://zenodo.org/doi/10.5281/zenodo.10371472)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/874022dc-7ea2-472f-bf88-3381b1364d37)

**Comment by bhushankhope** [comment]
Added this in PR #369

**Comment by libby-maier** [comment]
Perfect, thank you @bhushankhope!
