### ISSUE TITLE
Add Navigation options for Human Atlas Stories

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#350]
# To Do
- [x] Add a new menu item from the Training and Outreach menu that anchors to the new Human Atlas Stories section. This functionality should mimic what we did for Release Notes and Previews.
- [x] Add new button cards on the Training and Outreach Overview page that open links in new tabs to each Human Atlas Story.

## Resources
- Figma design file: [Training & Outreach Navbar](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-16569&mode=design&t=6HExnuuypswj31vy-4)
- Figma design file: [Training & Outreach Overview - New Human Atlas Stories section](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5282-8525&mode=design&t=6HExnuuypswj31vy-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/5a4e44b2-7425-4b32-b616-c72f1cf2bd29)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/f8c4cf94-10b0-47aa-b89c-f375f00a031d)

**Comment by bhushankhope** [comment]
Added this in PR #356

**Comment by libby-maier** [comment]
@bhushankhope & @bherr2:

The anchor functionality for the global navigation menu items Release Notes, Human Atlas Stories, and Previews only functions when users are on the page. Is it possible to make this function globally?

![EAC26078-19B5-48E1-AE5B-B9343E0C3329](https://github.com/cns-iu/humanatlas.io/assets/97060856/0192b633-1316-4766-9dbc-cb96b0aeae56)

**Comment by bhushankhope** [comment]
Fixed this in PR #371
