### ISSUE TITLE
Remove 5th Release Notes button card from the Data Overview page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#351]
- [ ] Remove 5th Release Notes button card from [Data Overview page](https://humanatlas.io/overview-data). All release notes live on the Training & Outreach pages now.

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/f7e7fca3-eba7-4912-b05a-45ae2584b055)

**Comment by bhushankhope** [comment]
Fixed this in PR #366
