### ISSUE TITLE
Editorial board needs open in new functionality + broken link update

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#353]
# To Do

- [x] All links routing externally need to open in a new tab.
- [x] Update Marc's link to https://labs.pathology.jhu.edu/halushka/team/
- [x] Update Mike's link to https://med.stanford.edu/snyderlab/about.html

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/121aeacf-750c-4ea5-be11-e699d22ec468)

**Comment by bhushankhope** [comment]
Fixed this in PR #354
