### ISSUE TITLE
Add omaps count: omaps_release6.csv

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#357]
We need a new omaps release csv that has count in the same schema as:

https://github.com/cns-iu/humanatlas.io/blob/main/apps/ccf/src/assets/table-data/omaps_release5.csv

**Comment by emquardokus** [comment]
I only changed 2 lines OMAP-2 and OMAP-9 to point to v2.0 otherwise all others point to v1.4.
Attached file
[omaps_release6.csv](https://github.com/cns-iu/humanatlas.io/files/13640537/omaps_release6.csv)

**Comment by bherr2** [comment]
Great, thank you! @bhushankhope will integrate

**Comment by bhushankhope** [comment]
Added this in PR #362
