### ISSUE TITLE
New additions to the SOPs page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#379]
# New additions to the SOPs page

Update the Anatomical Structures and Cell-Type Segmentation:
- [ ] Add new planned SOP with no link: Segmentation of Single Cells and Anatomical Structures
- [ ] Add new link: [Running a Kaggle Competition](https://zenodo.org/records/10019550)

## Resources
- Google Doc: [HRA SOP Table of Contents](https://docs.google.com/document/d/1Q-Fyi1N1uSwFvE4FBpFL9kvylLSbpElxHaYEVvgucNs/edit)

## Correspondence
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/faf87cd2-ee71-4ebf-a69e-23a2a47ba31c)
![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/1aca8841-451c-44e7-94af-291918fad599)

**Comment by bhushankhope** [comment]
Added this in PR #381

**Comment by libby-maier** [comment]
Thank you!
