### ISSUE TITLE
Display # of 3D as per organ 

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#385]
Katy requested:

```
# of 3D as per organ - feature request

Please add this ad a table to

https://humanatlas.io/3d-reference-library

k
```

We need to explore how best to add this data (it can easily be retrieved from ccf-grlc, but there may be better options than a table).

**Comment by bherr2** [comment]
Yes, I believe it is. Has @katyb and I signed off on it? I want it to be more integrated with the 3d organ display on the same page ie somewhere in here:

![image](https://github.com/cns-iu/humanatlas.io/assets/34098595/d4f22938-cdb3-4ba5-9d9d-fdd4f3935686)

**Comment by libby-maier** [comment]
# Design work in progress
- Bruce [provided feedback](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s?node-id=4800:14977&mode=design#724701132) on this design and I updated the cards
- Aiming to reuse these in future UIs
  - Note: New text styles, color styles, drop shadow styles, and new fonts  are being used
- Passing to Katy for feedback or approval today

## Figma Design File
- [3D organ model cards](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5410-10529&mode=design&t=DbC99jobww6VDnmk-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/722bef0d-004c-4123-ba4f-c50619f4ae1f)

**Comment by libby-maier** [comment]
# Another iteration
- Organ icon buttons should probably be retired in this version of the HRA Portal
- Still waiting for feedback/approval from Katy at this time

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/76ac6ba8-d46b-406f-ad14-8c32c4f99d57)

**Comment by libby-maier** [comment]
Closing as not planned. Superseded by #232
