### ISSUE TITLE
Add HRA Diversity Dashboard

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/humanatlas.io#389]
Please add this figure to Human Reference Atlas Diversity in [https://humanatlas.io/release-notes/v1.4](https://www.google.com/url?q=https://humanatlas.io/release-notes/v1.4&sa=D&source=docs&ust=1707400594230879&usg=AOvVaw0r987BsZc1s5AWGkIAKgN2) or add a new menu item to [https://humanatlas.io](https://www.google.com/url?q=https://humanatlas.io&sa=D&source=docs&ust=1707400594231006&usg=AOvVaw03q47AGSuYrHNJM_yMjxvP) to get this covered more prominently.

Please contact me for hi-res version.

![image](https://github.com/cns-iu/humanatlas.io/assets/22821046/201ea7f8-7694-4ff9-a1fe-cde0e090eb4d)

**Comment by andreasbueckle** [comment]
@bhushankhope 
The Figma file is at https://www.figma.com/file/GIKR3xb5vAUgaEuxloZwpM/UI-Annotations?type=design&node-id=211%3A111&mode=dev&t=ACzfJYyrshrb4lud-1. You can find the graphic in the place below. As caption, please use:

"HRA Equity Dashboard. Blue bars represent male, red bars represent female. "

![image](https://github.com/cns-iu/humanatlas.io/assets/22821046/29dcce94-5a5d-4cf4-b4cb-19cd73aac671)

**Comment by bhushankhope** [comment]
Added in PR #392

**Comment by libby-maier** [comment]
Hi @bhushankhope,

We have a new figure for this and I removed the caption. The caption is in the new figure. Please see the [HRA Diversity section in Figma](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-15971&mode=design&t=OtdGzwZVOEYKiEQw-4) for this update. Thank you!


![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/7d61aaa1-20be-4074-bd1a-b89df205a6d7)

**Comment by bhushankhope** [comment]
added new image in PR #395

**Comment by libby-maier** [comment]
Looks great, thank you @bhushankhope!
