### ISSUE TITLE
ADD link to reference dataset for OMAP-8 placenta

### ISSUE THREAD

**Issue by emquardokus** [cns-iu/humanatlas.io#390]
Please add this link to the OMAP-8 placenta table for representative dataset https://humanatlas.io/omap
https://zenodo.org/records/10406597
<img width="984" alt="Screenshot 2024-02-08 at 2 00 28 PM" src="https://github.com/cns-iu/humanatlas.io/assets/47257000/b5c6d3ca-e28e-4566-9853-330e9a61bceb">

**Comment by bhushankhope** [comment]
Added in PR #391
