### ISSUE TITLE
Add routes to FTU Explorer to navbar & Tools Overview page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#393]
# Add routes to FTU Explorer to navbar & Tools Overview page
Routes need to be added to the [Functional Tissue Unit Explorer](https://apps.humanatlas.io/ftu-explorer/#/):
- [ ] Add FTU Explorer button to the navigation bar in the Tools menu
- [ ] Add FTU Explorer card button to Tools Overview page

## Design Notes
- FTU Explorer route: https://apps.humanatlas.io/ftu-explorer/#/
- External links always open in new tabs.
- This is a stakeholder request from Katy. Please prioritize, if possible.

## Resources
- Figma Design File: [Tools Overview Page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5383-9506&mode=design&t=4t6FtEisEUTextuU-4)
- Figma Design File: [Tools Navbar Menu](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=4800-16548&mode=design&t=4t6FtEisEUTextuU-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/c0f98407-d9ef-49a1-a0f0-572d5697dc8a)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/29a1af51-9fa7-4b96-94af-ec7abf8a4e31)

**Comment by bhushankhope** [comment]
Added in PR #396

**Comment by libby-maier** [comment]
Looks great, thanks @bhushankhope!
