### ISSUE TITLE
Add Kaggle 4 button card to Training & Outreach Overview

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#394]
# Add Kaggle 4 button card to Training & Outreach Overview
- Button card uses standard open in new page route to [Kaggle SenNet + HOA - Hacking the Human Vasculature in 3D](https://www.kaggle.com/competitions/blood-vessel-segmentation)
- Figma design file: [K4 Card on Training & Outreach](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5395-9515&mode=design&t=OtdGzwZVOEYKiEQw-4)

![image](https://github.com/cns-iu/humanatlas.io/assets/97060856/7e134872-3e6d-4739-aba6-3c61ca1d80a5)

**Comment by bhushankhope** [comment]
Added in PR #397
