### ISSUE TITLE
Updates for RUI page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#40]
Figma design file: https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=408%3A5559&t=1Ky2E8SH3dfZlJ0H-4
HRA Proofread document: https://docs.google.com/document/d/1vJ2sQTj1qER44z8X_sHMjmY0UatZBSs12oK8hFhdB5w/edit#heading=h.ahlalbj8jzqu
Updated RUI Google doc: https://docs.google.com/document/d/1wJ6ABESGJkYZt9_DazM_FwLqIKHXbjjNPt0QGhbYSCQ/edit

- [x] Remove CCF from title card title
- [x] Update overview text to below:
This Registration User Interface (RUI) supports the registration of three-dimensional (3D) tissue blocks within 3D reference organs. A first beta of the CCF RUI became available in October 2020. 3D reference organs are freely available on the HRA Portal in the [3D Reference Object Library](https://humanatlas.io/3d-reference-library?version=1.3&organ=Allen%20Brain), the ontology can be found on [BioPortal](https://bioportal.bioontology.org/ontologies/CCF), and the code is available on [GitHub](https://github.com/hubmapconsortium/ccf-ui). The registration data is used in current versions of the Common Coordinate Framework and the [Exploration User Interface (EUI)](https://hubmapconsortium.github.io/ccf-ui/) developed within HuBMAP.
- [x] Overview in text links - Labels and link routes:
3D Reference Object Library: https://humanatlas.io/3d-reference-library?version=1.3&organ=Allen%20Brain
BioPortal: https://bioportal.bioontology.org/ontologies/CCF
GitHub: https://github.com/hubmapconsortium/ccf-ui
Exploration User Interface (EUI): https://hubmapconsortium.github.io/ccf-ui/

**Comment by emquardokus** [comment]
All issues mentioned here were updated in this pull request: https://github.com/cns-iu/humanatlas.io/pull/41
