### ISSUE TITLE
4th release notes overlaps with footer on short screens

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#48]
![image](https://user-images.githubusercontent.com/34098595/210601471-5a7e78f4-3978-4fce-91aa-0ed970823b1f.png)

**Comment by libby-maier** [comment]
+1 @bherr2. Must scroll to the bottom of the page to see Contact Us and the Outro: 

![9E95DA82-B53F-4D1D-922C-0C0972D64389](https://user-images.githubusercontent.com/97060856/212109820-a005bb4d-8998-43ed-9435-47a175037ece.GIF)

**Comment by bherr2** [comment]
Yes, this needs updated to work better on different sizes of screens. Related to #44

**Comment by bherr2** [comment]
@libby-maier please review on prod. Looks fine to me. If you agree, you can close the issue.

**Comment by libby-maier** [comment]
Looks great! Thanks so much!
