### ISSUE TITLE
Other OMAP fixes

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#51]
@emquardokus will provide more pointed changes, but go back to the CCF Portal's [OMAP page](https://hubmapconsortium.github.io/ccf/pages/omap.html) and update content to be in better alignment with it.

**Comment by emquardokus** [comment]
- [ ] ADD template links to OMAP overview page like it was in CCF Portal
Download:[ OMAP Table Template harmonized with Antibody Validation Reports](https://hubmapconsortium.github.io/ccf/pages/omap-extras/omap-table-template.xlsx)
Download:[ OMAP Description Document Template](https://hubmapconsortium.github.io/ccf/pages/omap-extras/omap-description-document-template.docx)
