### ISSUE TITLE
Include URLs to 24h Event YouTube Videos

### ISSUE THREAD

**Issue by dw-dot** [cns-iu/humanatlas.io#66]
Add URLs from the videos in the [24-Hour Human Reference Atlas Event 2022 YouTube playlist](https://youtube.com/playlist?list=PL-CUnYVIy7DOVqQbrzhnLEtY8uoVHKXOI) to their respective hourly segments on [https://humanatlas.io/events/2022-24h/](https://humanatlas.io/events/2022-24h/).

Please place the URL under the segment title. See red arrow below for placement. 

![image](https://user-images.githubusercontent.com/85894883/211832410-90a64903-e353-43f8-a568-735d685ee7ad.png)

**Comment by bhushankhope** [comment]
Added URLs in PR [#67](https://github.com/cns-iu/humanatlas.io/pull/67)
