### ISSUE TITLE
2D & 3D pages: Fix the position of the page when clicking on a new organ

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#68]
## 2D & 3D pages: Fix the position of the page when clicking on a new organ

Currently, when clicking on a new organ in the 2D and 3D pages, the position of the page moves back to the top: 
![24C610C9-CB94-45E1-A78A-E748D41E1522](https://user-images.githubusercontent.com/97060856/212100127-5a8985a5-3b5e-4b70-b9e3-67ba5fdbe9f5.GIF)

The position on the page needs to stay the same when users click on a new organ, so they don't have to scroll back down to view the object, as specified in Figma:
![F2BA5119-6144-4405-8905-D3EDC5EBFD14](https://user-images.githubusercontent.com/97060856/212100705-0228da67-758a-4be7-a5a8-130a1d9a9b08.GIF)

**Comment by libby-maier** [comment]
This issue is happening again. Please fix the position of the page when the user clicks the scrollbar menu or an organ icon on both 2D & 3D pages.

**Comment by bhushankhope** [comment]
Fixed this in PR #223
