### ISSUE TITLE
Move ALL content out of HTML templates and into YAML content

### ISSUE THREAD

**Issue by bherr2** [cns-iu/humanatlas.io#70]
Any place where there is text/content in the HTML, it MUST instead come from the YAML content files and be structured such that a novice YAML editor (ie a content provider, not a programmer) can understand what data is in there and how to reasonably add, modify, and delete content.

Not highest priority, but this needs to be addressed in a timely manner. Too much stuff is intermingled, when there is a clear path for the content to be coming from the YAML.

**Comment by bhushankhope** [comment]
Completed
