### ISSUE TITLE
Add PNG download to 2D FTU page per Figma file

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#87]
# Add PNG download to 2D FTU page per Figma file

- [x] Add a PNG Download button on the [2D page](https://humanatlas.io/2d-ftu-illustrations?version=1.3&organ=Kidney)  per the Figma spec.

![image](https://user-images.githubusercontent.com/97060856/217292920-fd8a84cd-7dde-4bbb-ac73-baad8cb199ea.png)

## Resources
- [Google Drive Folder - 2D Illustrations](https://drive.google.com/drive/folders/1EPN0ivKNzQ6xeexbgJvZrFumkTGbc4HV)
- [Figma Design File](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=537%3A9085&t=KyVTj1ERhpoo8obc-4)
- [GitHub 2D Illustrations](https://github.com/hubmapconsortium/ccf-releases/tree/v1.3/v1.3/2d-ftu)

**Comment by bherr2** [comment]
We don't have pre-generated PNG files. Since we are using the SVGs directly for display we could theoretically convert to PNG on the browser on the fly, but I wonder if it would be better to pre-render at specific sizes. @katyb @libby-maier need a decision on this. We can't add PNG until we have PNG files...

**Comment by libby-maier** [comment]
Both Rachel and Katy requested PNGs be added. They live in [Google Drive](https://drive.google.com/drive/folders/1EPN0ivKNzQ6xeexbgJvZrFumkTGbc4HV). This button was added to the spec during the last illustrator visit in October.

**Comment by bherr2** [comment]
Ok, that's what I needed. @bhushankhope setup a PR on the ccf-releases pages to add the .png files to here: https://github.com/hubmapconsortium/ccf-releases/tree/main/v1.3/2d-ftu . Note that the filenames changed, so please update the png file names to match what is officially published (just with .png). Once merged, then you can easily link to them from the humanatlas portal.
