### ISSUE TITLE
Add HRA Metrics cards to landing page

### ISSUE THREAD

**Issue by libby-maier** [cns-iu/humanatlas.io#99]
# Add HRA Metrics cards to the landing page

- [x] Add 9 cards to the landing page featuring HRA metrics
- [x] Automate these metrics when possible (see the relevant correspondence section below and pair with @bherr2 to make this happen)
- [x] Ensure this is implemented for varying breakpoints

## Resources
- [Figma design file: Desktop metrics](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=3859-21201&t=C1OGn7VzDduuSqq0-4)
- [Figma design file: Mobile metrics](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas?node-id=3859-21323&t=C1OGn7VzDduuSqq0-4)

## Relevant correspondence 
![image](https://user-images.githubusercontent.com/97060856/223745662-440c6809-de4c-434d-bfa6-8f1996f3ecc0.png)

### Desktop
![image](https://user-images.githubusercontent.com/97060856/223747158-0071a989-d710-438d-9f54-e3d0d0aa9224.png)

### Mobile
![image](https://user-images.githubusercontent.com/97060856/223747631-7a616147-a865-4b8e-b768-81dc364a5ef4.png)

**Comment by libby-maier** [comment]
@bherr2 & @bhushankhope - Were you able to find a way to automate some of these metrics? If so, which ones? Thanks for all of your hard work!

Regarding the landing page breakpoints, this is what I see on my iPhone SE on iOS 16.3.1:
![img_6614_720](https://user-images.githubusercontent.com/97060856/228669622-55803ca6-dcef-4dfb-8a9f-77917c246fb9.png)
![img_6615_720](https://user-images.githubusercontent.com/97060856/228669636-df9e0d8b-b8ef-4143-ad11-5397e50a10fa.png)

Additionally, when the nav bar is expanded on mobile, I cannot scroll down to see other options if the menu extends past the initial viewpoint.

**Comment by bherr2** [comment]
No numbers are automated yet and not a high priority as the numbers only change every 6 months

**Comment by libby-maier** [comment]
Hi @bherr2 & @bhushankhope - I reviewed the staging site again today. Is it possible to correct the below spacing issue? Ideally, the cards will reduce in size so the user sees 3 cards in each row in every mobile breakpoint. Let me know if this isn't possible and we can collaborate on a different solution.
![img_6625_720](https://user-images.githubusercontent.com/97060856/229609285-1d3fea7a-1ba6-4b4e-8164-a4d59927b470.png)
